export interface RowDowNStampPrint {
    Arrival_QTY: number,
    Article: string,
    CGDate_Date: string,
    CGNO_Order_No: string,
    CLBH_Material_No:string,
    Color:string,
    Name_Material_Detail:string,
    Print_QTY:string,
    Purpose:string,
    QTY:number,
    Roll:number,
    Season:string,
    Size:string,
    ZLBH_Work_Order:string,
    cllb_Material_Type:string,
    dwbh_Units:string,
    ywpm_Material:string,
    ywsm_Production:string,
    zsdh_Supplier_No:string,
    zsywjc_Supplier:string,
}